# python adaptation_tent.py --cfg configs/config_brats.py --dataset PraNet --prompt box --gpu_ids "1"
# python adaptation_mt.py --cfg configs/config_brats.py --dataset PraNet --prompt box --gpu_ids "1"
# python adaptation_tent.py --cfg configs/config_brats.py --dataset PraNet --prompt point --gpu_ids "1"
# python adaptation_mt.py --cfg configs/config_brats.py --dataset PraNet --prompt point --gpu_ids "1"
# python adaptation_source.py --cfg configs/config_brats.py --dataset PraNet --prompt point --gpu_ids "1"
# python adaptation_source.py --cfg configs/config_brats.py --dataset PraNet --prompt box --gpu_ids "1"

# python adaptation_source.py --cfg configs/config_brats.py --dataset PraNet --prompt box --gpu_ids "1"
# python adaptation_upl.py --cfg configs/config_brats.py --dataset PraNet --prompt point --gpu_ids "1"
# python adaptation_upl.py --cfg configs/config_brats.py --dataset PraNet --prompt box --gpu_ids "1"
# python adaptation_upl.py --cfg configs/config_brats.py --dataset PraNet --prompt point --gpu_ids "1"
# python adaptation_upl.py --cfg configs/config_brats.py --dataset mbh --prompt box --gpu_ids "1"
# python adaptation_upl.py --cfg configs/config_brats.py --dataset mbh --prompt point --gpu_ids "1"
# python adaptation_upl.py --cfg configs/config_brats.py --dataset ISIC --prompt box --gpu_ids "1"
# python adaptation_upl.py --cfg configs/config_brats.py --dataset ISIC --prompt point --gpu_ids "1"

python adaptation_upl.py --cfg configs/config_brats.py --dataset PraNet --prompt box --gpu_ids "1"
python adaptation_mt.py --cfg configs/config_brats.py --dataset PraNet --prompt box --gpu_ids "1"
python adaptation_wesam.py --cfg configs/config_brats.py --dataset PraNet --prompt box --gpu_ids "1"
python adaptation_source.py --cfg configs/config_brats.py --dataset PraNet --prompt box --gpu_ids "1"
python adaptation_medsam.py --cfg configs/config_medsam.py --dataset PraNet --prompt box --gpu_ids "1"
python adaptation_tent.py --cfg configs/config_brats.py --dataset BraTS_SSA_t2f --prompt box --gpu_ids "1"
python adaptation_cotta.py --cfg configs/config_brats.py --dataset PraNet --prompt box --gpu_ids "1"
# python adaptation_tent.py --cfg configs/config_brats.py --dataset mbh --prompt point --gpu_ids "1"
# python adaptation_mt.py --cfg configs/config_brats.py --dataset mbh --prompt point --gpu_ids "1"
# python adaptation_wesam.py --cfg configs/config_brats.py --dataset mbh --prompt point --gpu_ids "1"
# python adaptation_source.py --cfg configs/config_brats.py --dataset mbh --prompt point --gpu_ids "1"
# python adaptation_medsam.py --cfg configs/config_medsam.py --dataset mbh --prompt point --gpu_ids "1"
# python adaptation_cotta.py --cfg configs/config_brats.py --dataset mbh --prompt point --gpu_ids "1"